import { useEffect, useRef, useState } from 'react';
import { Bot, Copy, FileText, Paperclip, Send, Sparkles, Trash2, UploadCloud, Eye, X, CalendarPlus, Database, PanelLeftClose, PanelLeftOpen } from 'lucide-react';
import { api } from '../lib/api';
import { useScope } from '../lib/useScope';
import { hasScopeId, scopeQuery } from '../lib/scope';

type Msg={id:string;role:'user'|'assistant';text:string;sources?:{title:string}[]};
type Doc={id:string;name:string;size:number;status:string;chars?:number};
type DocPreview={id:string;name:string;preview:string;chars:number;truncated:boolean;readOnly:true};
const starters=['Проанализируй текущий P&L и найди главные причины падения прибыли','Что сильнее всего отклонилось от плана?','Собери план действий для управляющего на сегодня','Проверь ФОТ: часы, производительность и стоимость отклонения'];
const supported=new Set(['pdf','docx','xlsx','xlsm','xls','csv','txt','md','json','png','jpg','jpeg','webp','tiff','bmp']);const MAX_DOC_BYTES=15*1024*1024;const KEY='sten_chat_v5';
function to64(file:File){return new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result);ok(s.includes(',')?s.split(',')[1]:s)};r.onerror=()=>no(r.error);r.readAsDataURL(file)})}

export default function AI(){
 const[scope]=useScope();const[messages,setMessages]=useState<Msg[]>(()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}});const[prompt,setPrompt]=useState('');const[docs,setDocs]=useState<Doc[]>([]);const[busy,setBusy]=useState(false);const[upload,setUpload]=useState(false);const[previewDoc,setPreviewDoc]=useState<DocPreview|null>(null);const[previewBusy,setPreviewBusy]=useState(false);const[docsCollapsed,setDocsCollapsed]=useState(()=>{try{return localStorage.getItem('sten_docs_collapsed')==='1'}catch{return false}});const[context,setContext]=useState<any>(null);const[contextAt,setContextAt]=useState('');const file=useRef<HTMLInputElement>(null);
 useEffect(()=>{localStorage.setItem(KEY,JSON.stringify(messages.slice(-80)))},[messages]);useEffect(()=>{try{localStorage.setItem('sten_docs_collapsed',docsCollapsed?'1':'0')}catch{}},[docsCollapsed]);
 const load=async()=>{try{const r=await api.get<{documents:Doc[]}>('/ai/documents');setDocs(r.documents||[]);const q=scopeQuery(scope);const[p,f]=await Promise.all([api.get<any>('/api/pnl?'+q),api.get<any>('/fot-analytics?'+q).catch(()=>null)]);setContext({pnl:p?.calculated?.fact||null,plan:p?.calculated?.plan||null,calculated:p?.calculated||null,labor:Array.isArray(f?.records)?f.records.filter((x:any)=>x.period===scope.period):[]});setContextAt(new Date().toISOString())}catch{setContext(null)}};
 useEffect(()=>{void load()},[scope.period,scope.projectId,scope.branchId,scope.restaurantId,scope.departmentId]);
 async function ask(value=prompt){const text=value.trim();if(!text||busy)return;setPrompt('');const nextMsgs=[...messages,{id:crypto.randomUUID(),role:'user' as const,text}];setMessages(nextMsgs);setBusy(true);try{const r=await api.post<any>('/ask',{question:text,messages:nextMsgs.map(m=>({role:m.role,content:m.text})),scope:{period:scope.period,project_id:scope.projectId??null,branch_id:scope.branchId??null,restaurant_id:scope.restaurantId??null,department_id:scope.departmentId??null},currentData:context});const p=r?.data??r;setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:String(p.answer??p.message??'Ответ не получен.'),sources:Array.isArray(p.sources)?p.sources:[]}] )}catch(e){setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:e instanceof Error?e.message:'Не удалось получить ответ.'}])}finally{setBusy(false)}}
 async function makeTask(m:Msg){setBusy(true);try{await api.post('/api/secretary/events',{title:'STEN · действие по аналитике',description:m.text,start_at:new Date(Date.now()+60*60*1000).toISOString(),event_type:'task',status:'planned',reminder_minutes:30});setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:'Действие передано в Секретарь на контроль через 1 час.'}] )}catch(e){setMessages(v=>[...v,{id:crypto.randomUUID(),role:'assistant',text:e instanceof Error?e.message:'Не удалось передать действие в Секретарь.'}] )}finally{setBusy(false)}}
 async function uploadFiles(list:FileList|null){if(!list||upload)return;setUpload(true);try{for(const f of Array.from(list).slice(0,6)){const ext=f.name.split('.').pop()?.toLowerCase();if(!ext||!supported.has(ext)){setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:'Формат «.'+(ext||'?')+'» не поддерживается.'}]);continue}if(f.size>MAX_DOC_BYTES)throw new Error(f.name+': файл больше 15 МБ');await api.post('/ai/documents/upload',{name:f.name,mimeType:f.type||'application/octet-stream',dataBase64:await to64(f)})}await load()}catch(e){setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:e instanceof Error?e.message:'Файл не обработан.'}])}finally{setUpload(false)}}
 async function showPreview(d:Doc){setPreviewBusy(true);try{const r=await api.get<DocPreview>('/ai/documents/'+d.id+'/preview');setPreviewDoc((r as any)?.data??r)}catch(e){setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:e instanceof Error?e.message:'Не удалось открыть содержимое документа.'}])}finally{setPreviewBusy(false)}}
 async function removeDoc(d:Doc){try{await api.delete('/ai/documents/'+d.id);await load()}catch(e){setMessages(m=>[...m,{id:crypto.randomUUID(),role:'assistant',text:e instanceof Error?e.message:'Не удалось удалить документ.'}])}}
 const readyCount=docs.filter(d=>d.status==='ready').length;
 return <div className="page"><div className="page-head"><div><span className="eyebrow"><span className="status-dot"/> AI · ДАННЫЕ → ДЕЙСТВИЯ</span><h1>STEN</h1><p>AI видит выбранный рабочий контур, текущий P&L и ФОТ. Ответ отделён от факта, а действие можно передать в Секретарь.</p></div><button className="secondary-button"onClick={()=>{setMessages([]);localStorage.removeItem(KEY)}}>Новый диалог</button></div>
 {!hasScopeId(scope)&&<div className="import-result warn">Для точного AI-контекста выберите рабочий контур в Настройках.</div>}
 <div className={'ai-grid '+(docsCollapsed?'docs-collapsed':'')}><aside className="docs-panel"><div className="panel-title"><FileText size={17}/> Документы <span>{docs.length}</span><button className="docs-toggle" onClick={()=>setDocsCollapsed(v=>!v)} aria-label="Скрыть документы">{docsCollapsed?<PanelLeftOpen size={15}/>:<PanelLeftClose size={15}/>}</button></div><div className="dashboard-note"><Database size={14}/> {contextAt?'P&L/ФОТ обновлены '+new Date(contextAt).toLocaleTimeString('ru-RU'):'Текущий финансовый контекст не загружен.'}</div><button className="upload-box"onClick={()=>file.current?.click()}disabled={upload}><UploadCloud size={22}/><b>{upload?'Сохраняем…':'Загрузить документ'}</b><small>PDF · Excel · DOCX · CSV · TXT · JSON · изображения · до 15 МБ</small></button><input ref={file}hidden type="file"multiple accept=".pdf,.docx,.xlsx,.xlsm,.xls,.csv,.txt,.md,.json,.png,.jpg,.jpeg,.webp,.tiff,.bmp"onChange={e=>{void uploadFiles(e.target.files);e.currentTarget.value=''}}/><div className="doc-list">{docs.length?docs.map(d=><div className="doc-row"key={d.id}><FileText size={16}/><div><b title={d.name}>{d.name}</b><small>{Math.round(d.size/1024)} КБ · {d.status==='ready'?'готов · '+(d.chars??0)+' символов':'статус: '+d.status}</small></div><button className="icon-button compact"onClick={()=>void showPreview(d)}disabled={previewBusy}aria-label={'Открыть документ '+d.name}><Eye size={14}/></button><button className="icon-button compact"onClick={()=>void removeDoc(d)}aria-label={'Удалить документ '+d.name}><Trash2 size={14}/></button></div>):<div className="empty">Документов пока нет.</div>}</div><p className="dashboard-note">Документы не меняют P&L автоматически. Запись в финансовый контур требует подтверждения.</p></aside>
 <section className="chat"><div className="chat-head"><div><b><span className="avatar small"><Sparkles size={13}/></span> STEN</b><small>{readyCount} документов готовы</small></div><span>факты · расчёты · действия</span></div><div className="chat-body">{!messages.length?<div className="welcome"><div className="welcome-mark"><Bot size={28}/></div><h2>Что разбираем?</h2><p>STEN получает текущие цифры выбранного контура и отвечает только в пределах подтверждённых данных.</p><div className="starter-grid">{starters.map(s=><button key={s}onClick={()=>void ask(s)}>{s}</button>)}</div></div>:messages.map(m=><article className={'message '+m.role}key={m.id}><div className="message-avatar">{m.role==='assistant'?<Sparkles size={14}/>:'Вы'}</div><div className="message-body"><div>{m.text}</div>{m.sources?.length?<small className="sources">Источники: {m.sources.map(s=>s.title).join(' · ')}</small>:null}{m.role==='assistant'&&<div className="quick-actions"><button className="copy"onClick={()=>void navigator.clipboard?.writeText(m.text)}><Copy size={13}/> Копировать</button><button className="copy"disabled={busy}onClick={()=>void makeTask(m)}><CalendarPlus size={13}/> В Секретарь</button></div>}</div></article>)}{busy&&<div className="typing"aria-label="STEN готовит ответ"><i/><i/><i/></div>}</div><div className="composer"><div className="composer-box"><button className="icon-button"onClick={()=>file.current?.click()}aria-label="Прикрепить документ"><Paperclip size={18}/></button><textarea value={prompt}onChange={e=>setPrompt(e.target.value)}onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void ask()}}}placeholder="Что сделать с текущими данными?"rows={1}/><button className="send"disabled={!prompt.trim()||busy}onClick={()=>void ask()}aria-label="Отправить"><Send size={18}/></button></div><small>Enter — отправить · Shift+Enter — новая строка</small></div></section></div>
 {previewDoc&&<div className="modal-backdrop"onMouseDown={e=>e.currentTarget===e.target&&setPreviewDoc(null)}><section className="modal-card document-preview"role="dialog"aria-modal="true"aria-labelledby="document-preview-title"><button className="modal-close"onClick={()=>setPreviewDoc(null)}aria-label="Закрыть"><X size={18}/></button><small>ПРЕДПРОСМОТР · ТОЛЬКО ЧТЕНИЕ</small><h2 id="document-preview-title">{previewDoc.name}</h2><div className="dashboard-note"><FileText size={14}/> Извлечено {previewDoc.chars} символов.</div><pre className="document-preview-text">{previewDoc.preview||'Содержимое не извлечено.'}</pre>{previewDoc.truncated&&<p className="muted">Показана первая часть содержимого.</p>}</section></div>}
 </div>;
}
