import { useEffect, useMemo, useState } from 'react';
import { useAnalyticsSettings } from '../lib/useAnalyticsSettings';
import { AlertTriangle, BarChart3, Database, RefreshCw, Settings2, GitBranch } from 'lucide-react';
import { api } from '../lib/api';
import { useScope } from '../lib/useScope';
import { scopeQuery } from '../lib/scope';

type Row = { article?: string; plan?: number | null; fact?: number | null; source?: string };
type Labor = { period: string; department: string; hours: number; amount: number };
const finite = (v: unknown) => typeof v === 'number' && Number.isFinite(v) ? v : undefined;
const money = (v: number | undefined) => finite(v) == null ? 'Нет данных' : new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(v!);
const pct = (v: number | undefined) => finite(v) == null ? 'Нет данных' : v!.toFixed(1).replace('.', ',') + ' %';
const delta = (v: number | undefined) => finite(v) == null ? '—' : (v! > 0 ? '+' : '') + new Intl.NumberFormat('ru-RU', { maximumFractionDigits: 0 }).format(v!);
const pick = (rows: Row[], terms: string[]) => rows.find(row => terms.some(term => String(row.article || '').toLowerCase().replace(/ё/g, 'е').includes(term)));

export default function Analytics() {
  const [scope] = useScope(); const [rows, setRows] = useState<Row[]>([]); const [labor, setLabor] = useState<Labor[]>([]);
  const { settings } = useAnalyticsSettings(); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [updatedAt, setUpdatedAt] = useState<string>('');
  async function load(){setLoading(true);setError('');try{const q=scopeQuery(scope);const [pnl,fot]=await Promise.all([api.get<any>('/api/pnl?'+q),api.get<any>('/fot-analytics?'+q)]);setRows(Array.isArray(pnl?.rows)?pnl.rows:[]);setLabor(Array.isArray(fot?.records)?fot.records.filter((x:Labor)=>x.period===scope.period):[]);setUpdatedAt(new Date().toISOString())}catch(e){setRows([]);setLabor([]);setError(e instanceof Error?e.message:'Не удалось загрузить аналитику.')}finally{setLoading(false)}}
  useEffect(()=>{void load()},[scope.period,scope.projectId,scope.branchId,scope.restaurantId,scope.departmentId]);
  const metrics=useMemo(()=>{const revenue=pick(rows,['выруч','revenue']),cogs=pick(rows,['себестоим','cogs']),laborRow=pick(rows,['фот','фонд оплаты','зарплат','payroll']),opex=pick(rows,['операцион','opex']);const r=finite(revenue?.fact),rp=finite(revenue?.plan),c=finite(cogs?.fact),cp=finite(cogs?.plan),l=finite(laborRow?.fact),lp=finite(laborRow?.plan),o=finite(opex?.fact),op=finite(opex?.plan);return{r,rp,c,cp,l,lp,o,op,revenueDelta:r!=null&&rp!=null?r-rp:undefined,cogsDelta:c!=null&&cp!=null?c-cp:undefined,laborDelta:l!=null&&lp!=null?l-lp:undefined,opexDelta:o!=null&&op!=null?o-op:undefined,ebitda:r!=null&&c!=null&&l!=null&&o!=null?r-c-l-o:undefined,ebitdaPlan:rp!=null&&cp!=null&&lp!=null&&op!=null?rp-cp-lp-op:undefined,foodCost:r!=null&&c!=null?c/r*100:undefined,laborCost:r!=null&&l!=null?l/r*100:undefined};},[rows]);
  const laborRows=useMemo(()=>{const grouped=new Map<string,{hours:number;amount:number}>();labor.forEach(x=>{const k=x.department||'Без отдела';const v=grouped.get(k)||{hours:0,amount:0};v.hours+=Number(x.hours)||0;v.amount+=Number(x.amount)||0;grouped.set(k,v)});return[...grouped.entries()].sort((a,b)=>b[1].amount-a[1].amount)},[labor]);
  const totalHours=laborRows.reduce((s,[,v])=>s+v.hours,0); const totalPayroll=laborRows.reduce((s,[,v])=>s+v.amount,0);
  const revenuePerHour=metrics.r!=null&&totalHours>0?metrics.r/totalHours:undefined; const laborPerHour=totalHours>0?totalPayroll/totalHours:undefined;
  const forecast=useMemo(()=>{if(!settings.forecast||metrics.r==null)return undefined;const now=new Date(),[y,m]=scope.period.split('-').map(Number);if(now.getFullYear()!==y||now.getMonth()+1!==m)return undefined;const days=new Date(y,m,0).getDate();return metrics.r/now.getDate()*days},[metrics.r,scope.period,settings.forecast]);
  const gaps=[metrics.c==null?'COGS / себестоимость':null,metrics.l==null?'ФОТ':null,metrics.o==null?'OPEX':null,!laborRows.length?'ФОТ по часам':null,'Продажи по гостям/чекам','Daypart и каналы','Menu Engineering'].filter(Boolean) as string[];
  const driver=(label:string,f:number|undefined,p:number|undefined,sign=-1)=>{const d=f!=null&&p!=null?f-p:undefined;const impact=d==null?undefined:label==='Выручка'?d:sign*d;return <div key={label}><b>{label}</b><span>{money(f)} ₽</span><span>{money(p)} ₽</span><strong className={impact==null ? '' : impact > 0 ? 'positive' : 'negative'}>{impact==null ? '—' : (impact>=0?'+':'') + money(impact) + ' ₽'}</strong><small>{d==null?'Нет расчёта':'факт-план: '+delta(d)+' ₽'}</small></div>};
  return <div className="page analytics-page">
    <div className="page-head"><div><span className="eyebrow"><BarChart3 size={12}/> АНАЛИТИЧЕСКИЙ КОНТУР</span><h1>Аналитика</h1><p>Что произошло → почему → где деньги → какое действие следует проверить.</p></div><button className="secondary-button"onClick={()=>void load()}disabled={loading}><RefreshCw size={15}/>Обновить</button></div>
    {error&&<div className="panel empty-state"><b>Не удалось обновить отчёт</b><span>{error}</span></div>}
    {loading?<div className="panel empty">Загружаем аналитический отчёт…</div>:<>
      {settings.financial&&<section className="analytics-summary"><div><span className="eyebrow">ИТОГ ПЕРИОДА</span><p>Выручка {money(metrics.r)} ₽ · EBITDA {money(metrics.ebitda)} ₽ · Food Cost {pct(metrics.foodCost)} · Labor Cost {pct(metrics.laborCost)}</p></div><div className="analytics-summary-delta"><small>Δ EBITDA к плану</small><strong>{metrics.ebitda==null||metrics.ebitdaPlan==null?'Нет данных':delta(metrics.ebitda-metrics.ebitdaPlan)+' ₽'}</strong><span>Расчёт из подтверждённых P&L статей</span></div></section>}
      {settings.financial&&<section className="panel analytics-report-section"><div className="panel-title"><GitBranch size={16}/> Driver Tree · EBITDA</div><div className="analytics-report-table driver-tree"><div className="analytics-report-head"><span>Драйвер</span><span>Факт</span><span>План</span><span>Δ</span></div>{driver('Выручка',metrics.r,metrics.rp,1)}{driver('COGS',metrics.c,metrics.cp,-1)}{driver('ФОТ',metrics.l,metrics.lp,-1)}{driver('OPEX',metrics.o,metrics.op,-1)}<div className="finance-total-row"><b>Изменение EBITDA</b><span>—</span><span>—</span><strong>{metrics.ebitda==null||metrics.ebitdaPlan==null?'Нет данных':delta(metrics.ebitda-metrics.ebitdaPlan)+' ₽'}</strong><small>Выручка − COGS − ФОТ − OPEX</small></div></div><p className="dashboard-note">Дерево показывает вклад отклонений статей в изменение EBITDA. Это математическая декомпозиция, а не доказанная операционная причина.</p></section>}
      {settings.financial&&<section className="panel analytics-report-section"><div className="panel-title">Финансовый контур</div><div className="analytics-report-table"><div className="analytics-report-head"><span>Показатель</span><span>Факт</span><span>План</span><span>Состояние</span></div><div><b>Выручка</b><span>{money(metrics.r)} ₽</span><span>{money(metrics.rp)} ₽</span><strong>{metrics.revenueDelta==null?'Нет сравнения':(metrics.revenueDelta>=0?'Выше':'Ниже')+' плана на '+money(Math.abs(metrics.revenueDelta))+' ₽'}</strong></div><div><b>Food Cost</b><span>{pct(metrics.foodCost)}</span><span>Порог {settings.foodTarget}%</span><strong>{metrics.foodCost==null?'Нет данных':metrics.foodCost>settings.foodTarget?'Выше порога':'В пределах порога'}</strong></div><div><b>Labor Cost</b><span>{pct(metrics.laborCost)}</span><span>Порог {settings.laborTarget}%</span><strong>{metrics.laborCost==null?'Нет данных':metrics.laborCost>settings.laborTarget?'Выше порога':'В пределах порога'}</strong></div></div></section>}
      {settings.labor&&<section className="panel analytics-report-section"><div className="panel-title">ФОТ → часы → производительность → стоимость</div>{laborRows.length?<><div className="analytics-kpi-strip"><div><small>Часы</small><strong>{totalHours.toLocaleString('ru-RU',{maximumFractionDigits:1})}</strong><span>Источник ФОТ</span></div><div><small>ФОТ</small><strong>{money(totalPayroll)} ₽</strong><span>Факт</span></div><div><small>Выручка / час</small><strong>{money(revenuePerHour)} ₽</strong><span>Выручка ÷ часы</span></div><div><small>Стоимость часа</small><strong>{money(laborPerHour)} ₽</strong><span>ФОТ ÷ часы</span></div><div><small>Δ ФОТ</small><strong>{money(metrics.laborDelta)} ₽</strong><span>Факт − план</span></div></div><div className="analytics-report-table labor-table"><div className="analytics-report-head"><span>Подразделение</span><span>Часы</span><span>ФОТ</span><span>₽ / час</span></div>{laborRows.map(([d,v])=><div key={d}><b>{d}</b><span>{v.hours.toLocaleString('ru-RU',{maximumFractionDigits:1})} ч</span><span>{money(v.amount)} ₽</span><strong>{v.hours?money(v.amount/v.hours)+' ₽':'Нет данных'}</strong></div>)}</div></>:<div className="empty">Нет подтверждённых часов ФОТ. Производительность не моделируется.</div>}</section>}
      {settings.forecast&&<section className="panel analytics-report-section"><div className="panel-title">Прогноз темпа</div><div className="analytics-summary"><div><span className="eyebrow">RUN-RATE</span><p>{forecast==null?'Доступен только для текущего месяца при наличии факта выручки.':'При сохранении текущего дневного темпа выручка составит '+money(forecast)+' ₽.'}</p></div></div></section>}
      <section className="panel analytics-report-section"><div className="panel-title"><Database size={16}/> Центр данных</div><div className="analytics-report-table"><div className="analytics-report-head"><span>Источник</span><span>Что подтверждает</span><span>Формула / правило</span><span>Обновлено</span></div><div><b>P&L API</b><span>Выручка, COGS, ФОТ, OPEX</span><span>Статья → факт / план</span><strong>{updatedAt?new Date(updatedAt).toLocaleTimeString('ru-RU'):'—'}</strong></div><div><b>ФОТ API</b><span>Часы и начисления по подразделениям</span><span>ФОТ ÷ часы = ₽/час</span><strong>{updatedAt?new Date(updatedAt).toLocaleTimeString('ru-RU'):'—'}</strong></div><div><b>STEN calculator</b><span>EBITDA и маржи</span><span>Revenue − COGS − ФОТ − OPEX</span><strong>детерминированно</strong></div></div><p className="dashboard-note">«Обновлено» означает последний успешный запрос STEN. Серверная дата источника появится после добавления provenance/freshness в API.</p></section>
      <section className="analytics-gap-section"><div className="analytics-gap-head"><div><span className="eyebrow">КАЧЕСТВО ДАННЫХ</span><h2>Что ещё не подключено</h2></div><AlertTriangle size={17}/></div><div className="analytics-gap-list">{gaps.map(g=><span key={g}>{g}</span>)}</div><p>Отсутствующий источник не превращается в ноль. Следующий слой — продажи: гости, чеки, средний чек, daypart и каналы.</p></section>
      <div className="analytics-footer"><Settings2 size={15}/><span>Рабочий контур и пороги задаются в Настройки → Аналитика. Источник и формула показаны рядом с расчётом.</span></div>
    </>}
  </div>;
}
