import{useEffect,useMemo,useState}from'react';import{ArrowDownRight,ArrowUpRight,RefreshCw,WalletCards}from'lucide-react';import{api}from'../lib/api';import ScopeBar from'../components/ScopeBar';import{scopeQuery}from'../lib/scope';import{useScope}from'../lib/useScope';import{formatMoney,formatPercent}from'../lib/format';import{calculateFinance,FinanceInput}from'../lib/financeCalculator';

type Row={article:string;plan?:number|null;fact?:number|null;source?:string};
const find=(rows:Row[],keys:string[])=>rows.find(r=>keys.some(k=>String(r.article||'').toLocaleLowerCase('ru-RU').includes(k)));
const num=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v:undefined;
function input(rows:Row[],fact:boolean):FinanceInput{
 const get=(keys:string[])=>num(find(rows,keys)?.[fact?'fact':'plan']);
 return{revenue:get(['выруч','revenue']),cogs:get(['себесто','cogs','фудкост']),payroll:get(['фот','зарплат','персон','personnel']),opex:get(['opex','операцион','аренд']),depreciation:get(['амортиза','depreciation']),interest:get(['процент','interest']),tax:get(['налог','tax']),other:get(['проч','other'])};
}
const metric=(label:string,value:number|undefined,plan:number|undefined)=>({label,value,plan,delta:value!==undefined&&plan!==undefined?value-plan:undefined});
export default function Finances(){
 const[scope,setScope]=useScope(),[rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 const load=()=>{setLoading(true);setError('');api.get<any>('/api/pnl?'+scopeQuery(scope)).then(r=>{const d=r?.rows?r:r?.data??r;setRows(Array.isArray(d.rows)?d.rows:[])}).catch(e=>{setRows([]);setError(e instanceof Error?e.message:'Финансовые данные недоступны')}).finally(()=>setLoading(false))};
 useEffect(load,[scope.period,scope.projectId,scope.branchId,scope.restaurantId,scope.departmentId]);
 const fact=useMemo(()=>calculateFinance(input(rows,true)),[rows]);
 const plan=useMemo(()=>calculateFinance(input(rows,false)),[rows]);
 const metrics=[metric('Выручка',fact.revenue,plan.revenue),metric('Себестоимость',fact.cogs,plan.cogs),metric('ФОТ',fact.payroll,plan.payroll),metric('OPEX',fact.opex,plan.opex),metric('EBITDA',fact.ebitda,plan.ebitda),metric('Чистая прибыль',fact.netProfit,plan.netProfit)];
 const belowEbitda=(fact.depreciation!==undefined&&fact.interest!==undefined&&fact.tax!==undefined&&fact.other!==undefined)?fact.depreciation+fact.interest+fact.tax+fact.other:undefined;
 return <div className="page"><div className="page-head"><div><span className="eyebrow">ФИНАНСОВОЕ ЯДРО</span><h1>Финансы</h1><p>Детерминированный расчёт из подтверждённого P&L выбранной области. Нет факта — нет нулевого значения.</p></div><button className="secondary-button"onClick={load}><RefreshCw size={16}/>Обновить</button></div>{error&&<div className="import-result warn">{error}</div>}<div className="metric-grid">{metrics.map((m,i)=><div className="metric-card"key={m.label}><div className="metric-icon">{i===0?<WalletCards size={18}/>:i<2?<ArrowUpRight size={18}/>:<ArrowDownRight size={18}/>}</div><small>{m.label}</small><strong>{loading?'—':formatMoney(m.value)}</strong><span>план {formatMoney(m.plan)} · отклонение {formatMoney(m.delta)}</span></div>)}</div><div className="two-col"><section className="panel"><div className="panel-title">Финансовая цепочка <span>{scope.period}</span></div><div className="finance-chain"><div><small>Выручка</small><b>{formatMoney(fact.revenue)}</b></div><div><small>− Себестоимость</small><b>{formatMoney(fact.cogs)}</b></div><div><small>= Валовая прибыль</small><b>{formatMoney(fact.grossProfit)}</b></div><div><small>− ФОТ</small><b>{formatMoney(fact.payroll)}</b></div><div><small>− OPEX</small><b>{formatMoney(fact.opex)}</b></div><div><small>= EBITDA</small><b>{formatMoney(fact.ebitda)}</b></div><div><small>− Амортизация / проценты / налоги / прочее</small><b>{formatMoney(belowEbitda)}</b></div><div><small>= Чистая прибыль</small><b>{formatMoney(fact.netProfit)}</b></div></div></section><section className="panel"><div className="panel-title">Контроль маржи</div><div className="variance-row"><span>Food cost (себестоимость / выручка)</span><b>{formatPercent(fact.foodCostPct)}</b></div><div className="variance-row"><span>ФОТ / выручка</span><b>{formatPercent(fact.laborCostPct)}</b></div><div className="variance-row"><span>OPEX / выручка</span><b>{formatPercent(fact.opexPct)}</b></div><div className="variance-row"><span>EBITDA margin</span><b>{formatPercent(fact.ebitdaMargin)}</b></div><div className="variance-row"><span>Net margin</span><b>{formatPercent(fact.netMargin)}</b></div><p className="dashboard-note">Источник всех сумм: P&L выбранной области и периода. Расчёт выполнен детерминированным калькулятором; пустые входы не заменяются нулём. Если выручка растёт, а EBITDA падает — сравните доли «Food cost», «ФОТ / выручка» и «OPEX / выручка» с планом на странице P&L: рост доли расхода при той же выручке и есть причина.</p></section></div></div>
}