import{useEffect,useMemo,useState}from'react';
import{RefreshCw,WalletCards,AlertTriangle}from'lucide-react';
import{api}from'../lib/api';
import{scopeQuery}from'../lib/scope';
import{useScope}from'../lib/useScope';
import{formatMoney,formatPercent}from'../lib/format';
import{calculateFinance,FinanceInput}from'../lib/financeCalculator';
type Row={article:string;plan?:number|null;fact?:number|null;source?:string};
const find=(rows:Row[],keys:string[])=>rows.find(r=>keys.some(k=>String(r.article||'').toLocaleLowerCase('ru-RU').includes(k)));
const num=(v:number|null|undefined)=>typeof v==='number'&&Number.isFinite(v)?v:undefined;
function input(rows:Row[],fact:boolean):FinanceInput{const get=(keys:string[])=>num(find(rows,keys)?.[fact?'fact':'plan']);return{revenue:get(['выруч','revenue']),cogs:get(['себесто','cogs','фудкост']),payroll:get(['фот','зарплат','персон','personnel']),opex:get(['opex','операцион','аренд']),depreciation:get(['амортиза','depreciation']),interest:get(['процент','interest']),tax:get(['налог','tax']),other:get(['проч','other'])}}
export default function Finances(){
 const[scope]=useScope();const[rows,setRows]=useState<Row[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const load=()=>{setLoading(true);setError('');api.get<any>('/api/pnl?'+scopeQuery(scope)).then(r=>{const d=r?.rows?r:r?.data??r;setRows(Array.isArray(d.rows)?d.rows:[])}).catch(e=>{setRows([]);setError(e instanceof Error?e.message:'Финансовые данные недоступны')}).finally(()=>setLoading(false))};
 useEffect(load,[scope.period,scope.projectId,scope.branchId,scope.restaurantId,scope.departmentId]);
 const fact=useMemo(()=>calculateFinance(input(rows,true)),[rows]);const plan=useMemo(()=>calculateFinance(input(rows,false)),[rows]);
 const chain=[['Выручка',fact.revenue],['− Себестоимость',fact.cogs],['= Валовая прибыль',fact.grossProfit],['− ФОТ',fact.payroll],['− OPEX',fact.opex],['= EBITDA',fact.ebitda],['− Амортизация / проценты / налоги / прочее',fact.depreciation!==undefined&&fact.interest!==undefined&&fact.tax!==undefined&&fact.other!==undefined?fact.depreciation+fact.interest+fact.tax+fact.other:undefined],['= Чистая прибыль',fact.netProfit]] as [string,number|undefined][];
 const gaps=[fact.cogs==null?'Себестоимость / COGS':null,fact.payroll==null?'ФОТ':null,fact.opex==null?'OPEX':null,fact.depreciation==null?'Амортизация':null,fact.interest==null?'Проценты':null,fact.tax==null?'Налоги':null].filter(Boolean) as string[];
 const delta=(a:number|undefined,b:number|undefined)=>a!==undefined&&b!==undefined?b-a:undefined;
 const planFor=(label:string)=>label.includes('Выручка')?plan.revenue:label.includes('Себестоимость')?plan.cogs:label.includes('Валовая')?plan.grossProfit:label.includes('ФОТ')?plan.payroll:label.includes('OPEX')?plan.opex:label.includes('EBITDA')?plan.ebitda:label.includes('Чистая')?plan.netProfit:undefined;
 return <div className="page analytics-page"><div className="page-head"><div><span className="eyebrow"><WalletCards size={12}/> ФИНАНСОВОЕ ЯДРО</span><h1>Финансы</h1><p>Осмысленный финансовый отчёт из P&L выбранного контура. Расчёты выполняются детерминированно, отсутствующие входы не заменяются нулём.</p></div><button className="secondary-button"onClick={load}disabled={loading}><RefreshCw size={15}/>Обновить</button></div>
 {error&&<div className="panel empty-state"><b>Финансовые данные недоступны</b><span>{error}</span></div>}
 {loading?<div className="panel empty">Загружаем финансовый отчёт…</div>:<>
 <section className="analytics-summary"><div><span className="eyebrow">ИТОГ ПЕРИОДА</span><p>{fact.revenue==null?'Недостаточно данных для финансового вывода.':'Выручка '+formatMoney(fact.revenue)+' · EBITDA '+formatMoney(fact.ebitda)+' · Чистая прибыль '+formatMoney(fact.netProfit)}</p></div><div className="analytics-summary-delta"><small>План / факт</small><strong>{formatMoney(fact.revenue)}</strong><span>{formatMoney(plan.revenue)} · Δ {formatMoney(delta(plan.revenue,fact.revenue))}</span></div></section>
 <section className="analytics-kpi-strip"><div><small>Выручка</small><strong>{formatMoney(fact.revenue)}</strong><span>План {formatMoney(plan.revenue)}</span></div><div><small>Food Cost</small><strong>{formatPercent(fact.foodCostPct)}</strong><span>План {formatPercent(plan.foodCostPct)}</span></div><div><small>Labor Cost</small><strong>{formatPercent(fact.laborCostPct)}</strong><span>План {formatPercent(plan.laborCostPct)}</span></div><div><small>EBITDA</small><strong>{formatMoney(fact.ebitda)}</strong><span>Маржа {formatPercent(fact.ebitdaMargin)}</span></div><div><small>Net Profit</small><strong>{formatMoney(fact.netProfit)}</strong><span>Маржа {formatPercent(fact.netMargin)}</span></div></section>
 <section className="panel analytics-report-section"><div className="panel-title">Финансовая цепочка · {scope.period}</div><div className="analytics-report-table finance-report-table"><div className="analytics-report-head"><span>Показатель</span><span>Факт</span><span>План</span><span>Δ</span></div>{chain.map(([label,value])=>{const pv=planFor(label);return <div key={label} className={label.startsWith('=')?'finance-total-row':''}><b>{label}</b><span>{formatMoney(value)}</span><span>{formatMoney(pv)}</span><strong>{formatMoney(delta(pv,value))}</strong></div>})}</div></section>
 <section className="panel analytics-report-section"><div className="panel-title">Контроль маржи</div><div className="analytics-report-table"><div className="analytics-report-head"><span>Показатель</span><span>Факт</span><span>План</span><span>Δ</span></div><div><b>Food Cost</b><span>{formatPercent(fact.foodCostPct)}</span><span>{formatPercent(plan.foodCostPct)}</span><strong>{formatPercent(delta(plan.foodCostPct,fact.foodCostPct))}</strong></div><div><b>ФОТ / выручка</b><span>{formatPercent(fact.laborCostPct)}</span><span>{formatPercent(plan.laborCostPct)}</span><strong>{formatPercent(delta(plan.laborCostPct,fact.laborCostPct))}</strong></div><div><b>OPEX / выручка</b><span>{formatPercent(fact.opexPct)}</span><span>{formatPercent(plan.opexPct)}</span><strong>{formatPercent(delta(plan.opexPct,fact.opexPct))}</strong></div><div><b>EBITDA margin</b><span>{formatPercent(fact.ebitdaMargin)}</span><span>{formatPercent(plan.ebitdaMargin)}</span><strong>{formatPercent(delta(plan.ebitdaMargin,fact.ebitdaMargin))}</strong></div><div><b>Net margin</b><span>{formatPercent(fact.netMargin)}</span><span>{formatPercent(plan.netMargin)}</span><strong>{formatPercent(delta(plan.netMargin,fact.netMargin))}</strong></div></div></section>
 {gaps.length>0&&<section className="analytics-gap-section"><div className="analytics-gap-head"><div><span className="eyebrow">КАЧЕСТВО ДАННЫХ</span><h2>Неполный финансовый контур</h2></div><AlertTriangle size={17}/></div><div className="analytics-gap-list">{gaps.map(x=><span key={x}>{x}</span>)}</div><p>Показатели ниже неполных входов остаются «Нет данных». STEN не делает вывод о прибыли там, где исходные статьи не подтверждены.</p></section>}
 <div className="analytics-footer"><span>Источник: P&L выбранной области и периода. Расчёт: единый финансовый калькулятор STEN.</span></div></>}</div>
}