import{useState}from'react';import{ArrowLeft,CheckCircle2,FileSpreadsheet,UploadCloud,X,Save,AlertTriangle}from'lucide-react';import{useNavigate}from'react-router-dom';import*as XLSX from'xlsx';import{api}from'../lib/api';import ScopeBar from'../components/ScopeBar';import{useScope}from'../lib/useScope';import{writePnlAndVerify}from'../lib/saveVerify';

type Row={id:string;article:string;label:string;plan:number|null;fact:number|null;source:string;sheet?:string;sourceRow?:number;sourceCellPlan?:string|null;sourceCellFact?:string|null;confidence?:number;requiresReview?:boolean};
function read64(f:File){return new Promise<string>((ok,no)=>{const r=new FileReader();r.onload=()=>{const s=String(r.result);ok(s.split(',')[1]||s)};r.onerror=()=>no(r.error);r.readAsDataURL(f)})}
type Preview={headers:string[];rows:(string|number|null)[][];sheet:string};
async function preview(f:File):Promise<Preview>{const data=await f.arrayBuffer();const wb=XLSX.read(data,{type:'array',cellDates:true});if(!wb.SheetNames.length)throw new Error('В Excel нет листов.');const sheet=wb.SheetNames[0];const rows=XLSX.utils.sheet_to_json<(string|number|null)[]>(wb.Sheets[sheet],{header:1,defval:null,raw:true}) as (string|number|null)[][];return{sheet,headers:(rows[0]||[]).map(x=>String(x??'')),rows:rows.slice(1,8)}}
const money=(n:number|null|undefined)=>typeof n==='number'&&Number.isFinite(n)?new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(n):'—';
export default function PnLImport(){const nav=useNavigate(),[file,setFile]=useState<File|null>(null),[p,setP]=useState<Preview|null>(null),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[saving,setSaving]=useState(false),[msg,setMsg]=useState(''),[msgKind,setMsgKind]=useState<'info'|'ok'|'warn'>('info'),[scope,setScope]=useScope();
async function choose(f:File|undefined){if(!f)return;if(!/\.(xlsx|xlsm|xls)$/i.test(f.name)){setMsg('Нужен файл Excel: XLSX, XLS или XLSM.');setMsgKind('warn');return}if(f.size>15*1024*1024){setMsg('Файл больше 15 МБ.');setMsgKind('warn');return}try{setFile(f);setRows([]);setMsg('');setMsgKind('info');setP(await preview(f))}catch(e){setMsg(e instanceof Error?e.message:'Не удалось прочитать Excel.');setMsgKind('warn')}}
async function importFile(){if(!file||busy)return;setBusy(true);setMsg('');setMsgKind('info');try{const r=await api.post<unknown>('/api/pnl/import',{period:scope.period,project_id:scope.projectId??null,branch_id:scope.branchId??null,restaurant_id:scope.restaurantId??null,department_id:scope.departmentId??null,name:file.name,mimeType:file.type,dataBase64:await read64(file)});const d=typeof r==='object'&&r!==null?r as {rows?:unknown}:{};
const list=Array.isArray(d.rows)?d.rows.filter((row):row is Omit<Row,'id'> & {id?:string}=>typeof row==='object'&&row!==null&&typeof (row as {article?:unknown}).article==='string').map((row,index)=>({...row,id:row.id||`import-${index}`})):[];setRows(list);if(list.length){const review=list.filter(r=>r.requiresReview);setMsg(review.length?('Excel разобран: '+list.length+' строк, из них '+review.length+' требуют уточнения. Исправьте классификацию перед записью в P&L.'):('Excel разобран: '+list.length+' статей. Это ещё НЕ записанные данные — проверьте План/Факт и подтвердите запись в P&L.'));setMsgKind('info')}else{setMsg('В файле не найдены статьи P&L. Проверьте названия строк (Выручка, Себестоимость, ФОТ, OPEX…) и подписи колонок (План / Факт).');setMsgKind('warn')}}catch(e){setMsg(e instanceof Error?e.message:'Импорт не выполнен');setMsgKind('warn')}finally{setBusy(false)}}
async function save(){if(!rows.length||saving||rows.some(r=>r.requiresReview))return;setSaving(true);setMsg('');setMsgKind('info');/* Явное подтверждение пользователя → POST → серверный readback → повторное чтение GET → сравнение строк. */const result=await writePnlAndVerify(scope,rows.map(r=>({article:r.article,plan:r.plan??null,fact:r.fact??null})));setMsg(result.ok?'Импортированные строки записаны в P&L и подтверждены повторным чтением сервера.':result.message);setMsgKind(result.ok?'ok':'warn');setSaving(false)}
return <div className="page"><div className="page-head"><div><span className="eyebrow">P&L · ИМПОРТ</span><h1>Загрузка Excel</h1><p>Preview → распознавание → явное подтверждение → P&L → повторная проверка сохранения.</p></div><button className="secondary-button"onClick={()=>nav('/pnl')}><ArrowLeft size={16}/> P&L</button></div><section className="panel import-panel"><button className="modal-close"onClick={()=>nav('/pnl')}aria-label="Закрыть"><X/></button><div className="import-icon"><FileSpreadsheet size={30}/></div><h2>{file?file.name:'Загрузить Excel'}</h2><p>Поддерживаются XLS/XLSX/XLSM · до 15 МБ.</p><label className="upload-box"><UploadCloud size={25}/><b>Выбрать файл</b><small>Строки P&L → План / Факт</small><input hidden type="file"accept=".xlsx,.xls,.xlsm"onChange={e=>{void choose(e.target.files?.[0]);e.currentTarget.value=''}}/></label>{p&&<div className="preview"><b>Предпросмотр исходного листа: {p.sheet}</b><div className="table-scroll"><table><thead><tr>{p.headers.slice(0,10).map((h,i)=><th key={i}>{h||'—'}</th>)}</tr></thead><tbody>{p.rows.map((row,i)=><tr key={i}>{p.headers.slice(0,10).map((_,j)=><td key={j}>{String(row[j]??'')}</td>)}</tr>)}</tbody></table></div></div>}{rows.length>0&&<div className="import-mapping"><div className="panel-title"><CheckCircle2 size={17}/> Распознанные строки <span>{rows.length}</span></div><div className="mapping-table"><div className="mapping-row mapping-head"><span>Статья</span><span>План</span><span>Факт</span><span>Источник</span></div>{rows.map(r=><div className="mapping-row"key={r.id}><div><b>{r.label||r.article}</b><small>{r.sheet||r.source} · строка {r.sourceRow||'—'} · {r.requiresReview?'Требует уточнения':`confidence ${Math.round((r.confidence??0)*100)}%`}</small></div><strong>{money(r.plan)}</strong><strong>{money(r.fact)}</strong><small>{r.sourceCellPlan||'—'} / {r.sourceCellFact||'—'}</small></div>)}</div><button className="primary-button wide"disabled={saving||rows.some(r=>r.requiresReview)}onClick={()=>void save()}><Save size={16}/>{saving?'Сохраняем…':'Подтвердить и записать в P&L'}</button></div>}{msg&&<div className={'import-result '+(msgKind==='warn'?'warn':msgKind==='ok'?'ok':'')}><AlertTriangle size={16}/>{msg}</div>}<button className="secondary-button wide"disabled={!file||busy}onClick={()=>void importFile()}>{busy?'Разбираем Excel…':'Разобрать Excel'}</button></section></div>}