import{useEffect,useRef,useState}from'react';import{CalendarDays,CheckCircle2,Clock3,Plus,RefreshCw,Trash2,X}from'lucide-react';import{api}from'../lib/api';
type Event={id:string;title:string;description?:string;event_type:string;start_at:string;end_at?:string;status:string;reminder_minutes?:number;location?:string};
export default function Secretary(){const titleRef=useRef<HTMLInputElement>(null);const[events,setEvents]=useState<Event[]>([]),[notes,setNotes]=useState<any[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[date,setDate]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState('');
const load=async()=>{setLoading(true);setError('');try{const now=new Date(),to=new Date(now.getTime()+31*86400000);const [e,n]=await Promise.all([api.get<any>('/api/secretary/events?from='+encodeURIComponent(now.toISOString())+'&to='+encodeURIComponent(to.toISOString())),api.get<any>('/api/secretary/notes')]);setEvents(e?.events||[]);setNotes(n?.notes||[])}catch(e){setError(e instanceof Error?e.message:'Секретарь недоступен')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);useEffect(()=>{if(!open)return;titleRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open]);
const create=async()=>{if(!title.trim()||!date)return;try{await api.post('/api/secretary/events',{title,description,start_at:new Date(date).toISOString(),event_type:'meeting',status:'planned',reminder_minutes:30});setTitle('');setDate('');setDescription('');setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Не удалось создать событие')}};
const [confirmId,setConfirmId]=useState<string|null>(null),[deleting,setDeleting]=useState(false);
const remove=async(id:string)=>{setDeleting(true);setError('');try{const r=await api.delete<any>('/api/secretary/events/'+id);const body=r?.data??r;if((body?.deleted??body?.confirmed)!==true)throw new Error('Сервер не подтвердил удаление события.');await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Не удалось удалить событие')}finally{setDeleting(false);setConfirmId(null)}};
return <div className="page"><div className="page-head"><div><span className="eyebrow">УПРАВЛЕНИЕ</span><h1>Секретарь</h1><p>Встречи, задачи, заметки и контроль ближайших событий в одном рабочем контуре.</p></div><div className="head-actions"><button className="secondary-button"onClick={()=>void load()}><RefreshCw size={16}/>Обновить</button><button className="primary-button"onClick={()=>setOpen(true)}><Plus size={16}/>Событие</button></div></div>
{error&&<div className="error">{error}</div>}<div className="secretary-grid"><section className="panel"><div className="panel-title"><CalendarDays size={17}/>Ближайшие события</div>{loading?<div className="empty">Загрузка…</div>:events.length?events.map(e=><div className="secretary-event"key={e.id}><div className="secretary-date"><b>{new Date(e.start_at).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'})}</b><small>{new Date(e.start_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small></div><div className="secretary-main"><strong>{e.title}</strong><span>{e.description||'Без описания'}{e.location?' · '+e.location:''}</span><small><Clock3 size={12}/>напоминание за {e.reminder_minutes??30} мин.</small></div>{confirmId===e.id
 ? <span style={{display:'flex',gap:4}}><button className="danger-button" disabled={deleting} onClick={()=>void remove(e.id)}>{deleting?'Удаляем…':'Удалить'}</button><button className="secondary-button" onClick={()=>setConfirmId(null)}>Отмена</button></span>
 : <button className="icon-button" aria-label="Удалить событие" onClick={()=>setConfirmId(e.id)}><Trash2 size={15}/></button>}</div>):<div className="empty">На ближайшие 31 день событий нет.</div>}</section>
<section className="panel"><div className="panel-title"><CheckCircle2 size={17}/>Заметки и итоги</div>{notes.length?notes.slice(0,12).map(n=><div className="secretary-note"key={n.id}><strong>{n.title||'Без названия'}</strong><span>{n.content}</span><small>{new Date(n.updated_at).toLocaleString('ru-RU')}</small></div>):<div className="empty">Заметок пока нет.</div>}</section></div>
{open&&<div className="modal-backdrop"onMouseDown={e=>e.currentTarget===e.target&&setOpen(false)}><section className="modal-card"role="dialog"aria-modal="true"aria-labelledby="secretary-modal-title"><button className="modal-close"onClick={()=>setOpen(false)}aria-label="Закрыть"><X size={18}/></button><small>НОВОЕ СОБЫТИЕ</small><h2 id="secretary-modal-title">Добавить встречу</h2><label>Название<input ref={titleRef} className="scope-input" value={title} onChange={e=>setTitle(e.target.value)}/></label><label>Дата и время<input className="scope-input" type="datetime-local" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Описание<textarea className="scope-input" value={description} onChange={e=>setDescription(e.target.value)}/></label><button className="primary-button wide"disabled={!title.trim()||!date}onClick={()=>void create()}>Сохранить</button></section></div>}</div>}