import{useEffect,useRef,useState}from'react';import{CalendarDays,CheckCircle2,Clock3,Plus,RefreshCw,Trash2,X}from'lucide-react';import{api}from'../lib/api';

type Event={id:string;title:string;description?:string;event_type:string;start_at:string;end_at?:string;status:string;reminder_minutes?:number;location?:string;updated_at?:string};
type Note={id:string;title?:string;content?:string;updated_at:string};

const startOfDay=(date:Date)=>{const d=new Date(date);d.setHours(0,0,0,0);return d};
const formatDate=(value:string)=>new Date(value).toLocaleDateString('ru-RU',{day:'2-digit',month:'short'});
const formatTime=(value:string)=>new Date(value).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'});
const dayKey=(value:string)=>{const d=new Date(value);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const timelineLabel=(value:string,today:Date,tomorrow:Date)=>{const d=new Date(value);if(dayKey(value)===dayKey(today.toISOString()))return'Сегодня';if(dayKey(value)===dayKey(tomorrow.toISOString()))return'Завтра';return d.toLocaleDateString('ru-RU',{weekday:'short',day:'2-digit',month:'short'}).replace(/^./,c=>c.toUpperCase())};

export default function Secretary(){const titleRef=useRef<HTMLInputElement>(null);const[events,setEvents]=useState<Event[]>([]),[notes,setNotes]=useState<Note[]>([]),[loading,setLoading]=useState(true),[open,setOpen]=useState(false),[title,setTitle]=useState(''),[date,setDate]=useState(''),[description,setDescription]=useState(''),[error,setError]=useState('');const[confirmId,setConfirmId]=useState<string|null>(null),[deleting,setDeleting]=useState(false);

const load=async()=>{setLoading(true);setError('');try{const now=startOfDay(new Date()),to=new Date(now.getTime()+7*86400000);const[e,n]=await Promise.all([api.get<any>('/api/secretary/events?from='+encodeURIComponent(now.toISOString())+'&to='+encodeURIComponent(to.toISOString())),api.get<any>('/api/secretary/notes?mine=1')]);setEvents(e?.events||[]);setNotes(n?.notes||[])}catch(e){setError(e instanceof Error?e.message:'Секретарь недоступен')}finally{setLoading(false)}};useEffect(()=>{void load()},[]);useEffect(()=>{if(!open)return;titleRef.current?.focus();const onKey=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false)};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[open]);

const create=async()=>{if(!title.trim()||!date)return;try{await api.post('/api/secretary/events',{title,description,start_at:new Date(date).toISOString(),event_type:'meeting',status:'planned',reminder_minutes:30});setTitle('');setDate('');setDescription('');setOpen(false);await load()}catch(e){setError(e instanceof Error?e.message:'Не удалось создать событие')}};

const remove=async(id:string)=>{setDeleting(true);setError('');try{const r=await api.delete<any>('/api/secretary/events/'+id);const body=r?.data??r;if((body?.deleted??body?.confirmed)!==true)throw new Error('Сервер не подтвердил удаление события.');await load();setError('')}catch(e){setError(e instanceof Error?e.message:'Не удалось удалить событие')}finally{setDeleting(false);setConfirmId(null)}};

const today=startOfDay(new Date()),tomorrow=new Date(today.getTime()+86400000),todayKey=dayKey(today.toISOString()),tomorrowKey=dayKey(tomorrow.toISOString());
const todayEvents=events.filter(e=>dayKey(e.start_at)===todayKey);
const inboxEvents=events.filter(e=>dayKey(e.start_at)!==todayKey).sort((a,b)=>new Date(a.start_at).getTime()-new Date(b.start_at).getTime());
const inboxNotes=[...notes].sort((a,b)=>new Date(b.updated_at).getTime()-new Date(a.updated_at).getTime());
const timelineDays=new Map<string,{label:string;events:Event[]}>();
for(const event of events){const key=dayKey(event.start_at);const eventDay=startOfDay(new Date(event.start_at));const diff=Math.floor((eventDay.getTime()-today.getTime())/86400000);if(diff<0||diff>=7)continue;const existing=timelineDays.get(key);if(existing)existing.events.push(event);else timelineDays.set(key,{label:timelineLabel(event.start_at,today,tomorrow),events:[event]})}
const timeline=[...timelineDays.entries()].sort((a,b)=>a[0].localeCompare(b[0])).map(([,day])=>day);

const renderEvent=(e:Event,compact=false)=><div className="secretary-event"key={e.id}><div className="secretary-date"><b>{formatDate(e.start_at)}</b><small>{formatTime(e.start_at)}</small></div><div className="secretary-main"><strong>{e.title}</strong>{!compact&&e.description&&<span>{e.description}</span>}{!compact&&e.location&&<span>{e.location}</span>}{!compact&&<small><Clock3 size={12}/>напоминание за {e.reminder_minutes??30} мин.</small>}</div>{!compact&&(confirmId===e.id?<span style={{display:'flex',gap:4}}><button className="danger-button"disabled={deleting}onClick={()=>void remove(e.id)}>{deleting?'Удаляем…':'Удалить'}</button><button className="secondary-button"onClick={()=>setConfirmId(null)}>Отмена</button></span>:<button className="icon-button"aria-label="Удалить событие"onClick={()=>setConfirmId(e.id)}><Trash2 size={15}/></button>)}</div>;

return <div className="page"><div className="page-head"><div><span className="eyebrow">ОПЕРАЦИИ · ЕЖЕДНЕВНИК</span><h1>Секретарь</h1><p>Ежедневник руководителя: события и личные заметки в одном рабочем контуре.</p></div><div className="head-actions"><button className="secondary-button"onClick={()=>void load()}><RefreshCw size={16}/>Обновить</button><button className="primary-button"onClick={()=>setOpen(true)}><Plus size={16}/>Новое событие</button></div></div>
{error&&<div className="error">{error}</div>}
<div className="secretary-grid"><section className="panel"><div className="panel-title"><CalendarDays size={17}/>Мой день <span className="muted">{today.toLocaleDateString('ru-RU',{day:'2-digit',month:'long'})}</span></div>{loading?<div className="empty">Загрузка…</div>:todayEvents.length?todayEvents.map(e=>renderEvent(e)):<div className="empty">На сегодня событий нет <button className="secondary-button"onClick={()=>setOpen(true)}>Добавить событие</button></div>}</section>
<section className="panel"><div className="panel-title"><CheckCircle2 size={17}/>Входящие</div>{loading?<div className="empty">Загрузка…</div>:inboxEvents.length||inboxNotes.length?<><div>{inboxEvents.map(e=>renderEvent(e))}</div>{inboxNotes.length>0&&<div>{inboxNotes.map(n=><div className="secretary-note"key={n.id}><strong>{n.title||'Без названия'}</strong><span>{n.content||''}</span><small>{new Date(n.updated_at).toLocaleString('ru-RU')}</small></div>)}</div>}</>:<div className="empty">Пока ничего нет</div>}</section></div>
<section className="panel secretary-timeline"><div className="panel-title"><CalendarDays size={17}/>Ближайшие 7 дней</div>{loading?<div className="empty">Загрузка…</div>:timeline.length?timeline.map(day=><div className="secretary-day"key={day.label}><div className="secretary-day-label">{day.label}</div><div className="secretary-day-events">{day.events.map(e=>renderEvent(e,true))}</div></div>):<div className="empty">На ближайшие 7 дней событий нет</div>}</section>
{open&&<div className="modal-backdrop"onMouseDown={e=>e.currentTarget===e.target&&setOpen(false)}><section className="modal-card"role="dialog"aria-modal="true"aria-labelledby="secretary-modal-title"><button className="modal-close"onClick={()=>setOpen(false)}aria-label="Закрыть"><X size={18}/></button><small>НОВОЕ СОБЫТИЕ</small><h2 id="secretary-modal-title">Добавить встречу</h2><label>Название<input ref={titleRef}className="scope-input"value={title}onChange={e=>setTitle(e.target.value)}/></label><label>Дата и время<input className="scope-input"type="datetime-local"value={date}onChange={e=>setDate(e.target.value)}/></label><label>Описание<textarea className="scope-input"value={description}onChange={e=>setDescription(e.target.value)}/></label><button className="primary-button wide"disabled={!title.trim()||!date}onClick={()=>void create()}>Сохранить</button></section></div>}</div>}