import{useEffect,useState}from'react';import{Check,Save}from'lucide-react';import{useAuth}from'../contexts/AuthContext';import{api}from'../lib/api';import WorkspaceSelector from'../components/WorkspaceSelector';import{useScope}from'../lib/useScope';import{useAnalyticsSettings,type AnalyticsSettings}from'../lib/useAnalyticsSettings';

type Theme='light'|'dark'|'system';type Metrics={revenue:boolean;cashCard:boolean;discounts:boolean;avgCheck:boolean;checks:boolean;primeCost:boolean;ebitda:boolean;deviation:boolean};
const TK='sten_theme_v5',BK='sten_blocks_v5';const defaults={dashboard:true,pnl:true,finances:true,budget:true};
const metricDefaults:Metrics={revenue:true,cashCard:true,discounts:true,avgCheck:true,checks:true,primeCost:true,ebitda:true,deviation:true};

export default function Settings(){
 const{signOut,user,refresh}=useAuth();const[scope,setScope]=useScope();
 const[theme,setTheme]=useState<Theme>((localStorage.getItem(TK)as Theme)||'system');
 const[blocks,setBlocks]=useState(()=>{try{return{...defaults,...JSON.parse(localStorage.getItem(BK)||'{}')}}catch{return{...defaults}}});
 const[profile,setProfile]=useState({firstName:user?.firstName||'',lastName:user?.lastName||'',position:user?.position||'',telegramChatId:user?.telegramChatId||''});
 const[profileSaving,setProfileSaving]=useState(false);const[profileMessage,setProfileMessage]=useState('');
 const[sendTime,setSendTime]=useState('21:00');const[metrics,setMetrics]=useState<Metrics>(metricDefaults);const[messengerMessage,setMessengerMessage]=useState('');const[messengerSaving,setMessengerSaving]=useState(false);
 const{settings:analytics,saving:analyticsSaving,error:analyticsError,savedAt:analyticsSavedAt,save:saveAnalytics}=useAnalyticsSettings();const[analyticsDraft,setAnalyticsDraft]=useState<AnalyticsSettings>(analytics);
 useEffect(()=>{setAnalyticsDraft(analytics)},[analytics]);
 useEffect(()=>{setProfile({firstName:user?.firstName||'',lastName:user?.lastName||'',position:user?.position||'',telegramChatId:user?.telegramChatId||'')},[user?.firstName,user?.lastName,user?.position,user?.telegramChatId]);
 useEffect(()=>{void(async()=>{try{const r=await api.get<any>('/api/messenger/settings');const s=r?.settings;if(s){setSendTime(s.send_time||'21:00');setMetrics({...metricDefaults,...(s.metrics||{})});if(!user?.telegramChatId&&s.telegram_chat_id)setProfile(v=>({...v,telegramChatId:s.telegram_chat_id}))}}catch{}})()},[user?.telegramChatId]);
 const setThemeValue=(t:Theme)=>{setTheme(t);localStorage.setItem(TK,t);document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t};
 const setBlock=(k:string,v:boolean)=>{const n={...blocks,[k]:v};setBlocks(n);localStorage.setItem(BK,JSON.stringify(n))};
 const saveProfile=async()=>{setProfileSaving(true);setProfileMessage('');try{const r=await api.put<any>('/api/profile',profile);if(r?.profile)setProfile({firstName:r.profile.firstName||'',lastName:r.profile.lastName||'',position:r.profile.position||'',telegramChatId:r.profile.telegramChatId||''});await refresh();setProfileMessage('Профиль сохранён.')}catch(e){setProfileMessage(e instanceof Error?e.message:'Не удалось сохранить профиль.')}finally{setProfileSaving(false)}};
 const saveMessenger=async()=>{setMessengerSaving(true);setMessengerMessage('');try{await api.post('/api/messenger/settings',{provider:'telegram',send_time:sendTime,scope:{period:scope.period,project_id:scope.projectId||'',branch_id:scope.branchId||'',restaurant_id:scope.restaurantId||'',department_id:scope.departmentId||''},metrics,telegram_chat_id:profile.telegramChatId||null,whatsapp_phone:null});setMessengerMessage('Отчёты сохранены.')}catch(e){setMessengerMessage(e instanceof Error?e.message:'Не удалось сохранить отчёты.')}finally{setMessengerSaving(false)}};
 const toggleMetric=(k:keyof Metrics)=>setMetrics(v=>({...v,[k]:!v[k]}));
 const labels:Record<keyof Metrics,string>={revenue:'Выручка',cashCard:'Наличные и карта',discounts:'Скидки',avgCheck:'Средний чек',checks:'Чеки',primeCost:'Себестоимость',ebitda:'EBITDA',deviation:'Отклонение от плана'};
 return <div className="page"><div className="page-head"><div><span className="eyebrow">МОЙ КАБИНЕТ</span><h1>Настройки</h1><p>Только то, что нужно для работы STEN.</p></div></div><div className="settings-grid">
 <WorkspaceSelector value={scope} onChange={setScope}/>
 <section className="panel"><h2>Мои данные</h2><p className="muted">Эти данные используются в профиле STEN и для отправки отчётов в Telegram.</p><div className="settings-field"><span>Имя</span><input value={profile.firstName} onChange={e=>setProfile(v=>({...v,firstName:e.target.value}))} placeholder="Александр"/></div><div className="settings-field"><span>Фамилия</span><input value={profile.lastName} onChange={e=>setProfile(v=>({...v,lastName:e.target.value}))} placeholder="Фамилия"/></div><div className="settings-field"><span>Должность</span><input value={profile.position} onChange={e=>setProfile(v=>({...v,position:e.target.value}))} placeholder="Операционный директор"/></div><div className="settings-field"><span>Telegram ID</span><input inputMode="numeric" value={profile.telegramChatId} onChange={e=>setProfile(v=>({...v,telegramChatId:e.target.value.replace(/[^\\d-]/g,'')}))} placeholder="Например, 123456789"/><small className="muted">Нужен, чтобы STEN мог отправлять Вам отчёты в Telegram.</small></div><button className="primary-button"disabled={profileSaving}onClick={()=>void saveProfile()}><Save size={16}/>{profileSaving?'Сохраняем…':'Сохранить данные'}</button>{profileMessage&&<div className="pnl-message ok">{profileMessage}</div>}</section>
 <section className="panel"><h2>Тема</h2><div className="choice-grid">{(['light','system','dark']as Theme[]).map(t=><button key={t}className={'choice '+(theme===t?'active':'')}onClick={()=>setThemeValue(t)}>{t==='light'?'Светлая':t==='dark'?'Тёмная':'Системная'}{theme===t&&<Check size={16}/>}</button>)}</div></section>
 <section className="panel"><h2>Рабочие разделы</h2><p className="muted">Можно убрать раздел из меню. Данные не удаляются.</p>{Object.entries<boolean>(blocks).map(([k,v])=><label className="toggle-row"key={k}><span><b>{({dashboard:'Обзор',pnl:'P&L',finances:'Финансы',budget:'Бюджет'}as Record<string,string>)[k]}</b><small>{v?'Показывать':'Скрыть'}</small></span><input type="checkbox"checked={v}onChange={e=>setBlock(k,e.target.checked)}/><i/></label>)}</section>
 <section className="panel messenger-settings"><h2>Отчёты в Telegram</h2><p className="muted">STEN будет отправлять выбранные показатели на указанный выше Telegram ID.</p><label className="settings-field"><span>Время отправки</span><input type="time"value={sendTime}onChange={e=>setSendTime(e.target.value)}/></label><div className="messenger-metrics">{(Object.keys(labels)as Array<keyof Metrics>).map(k=><label className="toggle-row"key={k}><span><b>{labels[k]}</b></span><input type="checkbox"checked={metrics[k]}onChange={()=>toggleMetric(k)}/><i/></label>)}</div><button className="primary-button"disabled={messengerSaving}onClick={()=>void saveMessenger()}><Save size={16}/>{messengerSaving?'Сохраняем…':'Сохранить отчёты'}</button>{messengerMessage&&<div className="pnl-message ok">{messengerMessage}</div>}</section>
 <section className="panel analytics-settings"><h2>Аналитика</h2><p className="muted">Выберите, какие показатели STEN использует в аналитике.</p><label className="toggle-row"><span><b>Финансовая аналитика</b><small>Выручка, себестоимость, ФОТ, прибыль и сигналы.</small></span><input type="checkbox"checked={analyticsDraft.financial}onChange={e=>setAnalyticsDraft(v=>({...v,financial:e.target.checked}))}/><i/></label><label className="toggle-row"><span><b>Аналитика ФОТ</b><small>Нагрузка и расходы на команду.</small></span><input type="checkbox"checked={analyticsDraft.labor}onChange={e=>setAnalyticsDraft(v=>({...v,labor:e.target.checked}))}/><i/></label><label className="toggle-row"><span><b>Прогноз месяца</b><small>Оценка результата текущего месяца по имеющимся данным.</small></span><input type="checkbox"checked={analyticsDraft.forecast}onChange={e=>setAnalyticsDraft(v=>({...v,forecast:e.target.checked}))}/><i/></label><label className="settings-field"><span>Порог себестоимости, %</span><input type="number"min="0"max="100"value={analyticsDraft.foodTarget}onChange={e=>setAnalyticsDraft(v=>({...v,foodTarget:Number(e.target.value)}))}/></label><label className="settings-field"><span>Порог ФОТ, %</span><input type="number"min="0"max="100"value={analyticsDraft.laborTarget}onChange={e=>setAnalyticsDraft(v=>({...v,laborTarget:Number(e.target.value)}))}/><button className="primary-button"disabled={analyticsSaving}onClick={()=>void saveAnalytics(analyticsDraft)}><Save size={16}/>{analyticsSaving?'Сохраняем…':'Сохранить аналитику'}</button>{analyticsError&&<div className="pnl-message error">{analyticsError}</div>}{analyticsSavedAt&&!analyticsError&&<div className="pnl-message ok">Аналитика сохранена.</div>}</section>
 <section className="panel"><h2>Сеанс</h2><p className="muted">{user?.email||'Ваша учётная запись'}</p><button className="danger-button"onClick={signOut}>Выйти из STEN</button></section>
 </div></div>}