import{useEffect,useState}from'react';import{Check,Save,Trash2}from'lucide-react';import{useAuth}from'../contexts/AuthContext';import{api}from'../lib/api';import WorkspaceSelector from'../components/WorkspaceSelector';import{useScope}from'../lib/useScope';
type Theme='light'|'dark'|'system';const TK='sten_theme_v5',BK='sten_blocks_v5',SK='sten_scope_v5',CK='sten_chat_v5';const defaults={dashboard:true,pnl:true,finances:true,budget:true};
type Messenger='telegram'|'whatsapp';type Metrics={revenue:boolean;cashCard:boolean;discounts:boolean;avgCheck:boolean;checks:boolean;primeCost:boolean;ebitda:boolean;deviation:boolean};
const metricDefaults:Metrics={revenue:true,cashCard:true,discounts:true,avgCheck:true,checks:true,primeCost:true,ebitda:true,deviation:true};
export default function Settings(){
 const{signOut}=useAuth();const[scope,setScope]=useScope();const readBlocks=()=>{try{return{...defaults,...JSON.parse(localStorage.getItem(BK)||'{}')}}catch{return{...defaults}}};
 type Skills={foodCost:number;laborCost:number;shiftHours:number;tone:'brief'|'expanded'|'official';documents:boolean;history:boolean;excludeCapex:boolean};
 const defaultSkills:Skills={foodCost:35,laborCost:30,shiftHours:12,tone:'brief',documents:true,history:true,excludeCapex:true};
 const[theme,setTheme]=useState<Theme>((localStorage.getItem(TK)as Theme)||'system');const[blocks,setBlocks]=useState(readBlocks);const[cleared,setCleared]=useState(false);const[skills,setSkills]=useState<Skills>(defaultSkills);const[skillsSaving,setSkillsSaving]=useState(false);const[skillsMessage,setSkillsMessage]=useState('');
 const[provider,setProvider]=useState<Messenger>('telegram');const[sendTime,setSendTime]=useState('21:00');const[telegramChat,setTelegramChat]=useState('');const[whatsappPhone,setWhatsappPhone]=useState('');const[metrics,setMetrics]=useState<Metrics>(metricDefaults);const[messengerMessage,setMessengerMessage]=useState('');const[messengerSaving,setMessengerSaving]=useState(false);
 useEffect(()=>{void (async()=>{try{const r=await api.get<{settings?:Skills}>('/api/ai/skills');if(r.settings)setSkills({...defaultSkills,...r.settings})}catch{}})()},[]);
 useEffect(()=>{void (async()=>{try{const r=await api.get<any>('/api/messenger/settings');const s=r?.settings;if(s){setProvider(s.provider==='whatsapp'?'whatsapp':'telegram');setSendTime(s.send_time||'21:00');setTelegramChat(s.telegram_chat_id||'');setWhatsappPhone(s.whatsapp_phone||'');setMetrics({...metricDefaults,...(s.metrics||{})})}}catch{}})()},[]);
 const setThemeValue=(t:Theme)=>{setTheme(t);localStorage.setItem(TK,t);document.documentElement.dataset.theme=t==='system'?(matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light'):t};
 const setBlock=(k:string,v:boolean)=>{const n={...blocks,[k]:v};setBlocks(n);localStorage.setItem(BK,JSON.stringify(n))};
 const clear=async()=>{for(const k of [SK,CK])localStorage.removeItem(k);try{if('caches'in window)for(const k of await caches.keys())if(k.includes('sten'))await caches.delete(k)}catch{}setCleared(true);setTimeout(()=>setCleared(false),4000)};
 const saveMessenger=async()=>{setMessengerSaving(true);setMessengerMessage('');try{await api.post('/api/messenger/settings',{provider,send_time:sendTime,scope:{period:scope.period,project_id:scope.projectId||'',branch_id:scope.branchId||'',restaurant_id:scope.restaurantId||'',department_id:scope.departmentId||''},metrics,telegram_chat_id:telegramChat||null,whatsapp_phone:whatsappPhone||null});setMessengerMessage('Настройки мессенджера сохранены.')}catch(e){setMessengerMessage(e instanceof Error?e.message:'Не удалось сохранить настройки.')}finally{setMessengerSaving(false)}};
 const toggleMetric=(k:keyof Metrics)=>setMetrics(v=>({...v,[k]:!v[k]}));
 const setSkill=<K extends keyof Skills>(k:K,v:Skills[K])=>setSkills(prev=>({...prev,[k]:v}));
 const saveSkills=async()=>{setSkillsSaving(true);setSkillsMessage('');try{const r=await api.put<unknown>('/api/ai/skills',skills);const body=typeof r==='object'&&r!==null?r as{settings?:Skills}:{};setSkills(body.settings?{...defaultSkills,...body.settings}:skills);setSkillsMessage('AI Skills сохранены на сервере.')}catch(e){setSkillsMessage(e instanceof Error?e.message:'Не удалось сохранить AI Skills.')}finally{setSkillsSaving(false)}};
 const metricLabels:Record<keyof Metrics,string>={revenue:'Выручка',cashCard:'Наличные / карта',discounts:'Скидки',avgCheck:'Средний чек',checks:'Чеки',primeCost:'Prime Cost',ebitda:'EBITDA',deviation:'Отклонение от плана'};
 return <div className="page"><div className="page-head"><div><span className="eyebrow">СИСТЕМА</span><h1>Настройки</h1><p>Персональный кабинет: тема, рабочие блоки, отчёты и локальные данные.</p></div></div><div className="settings-grid">
 <WorkspaceSelector value={scope} onChange={setScope}/><section className="panel"><h2>Тема</h2><div className="choice-grid">{(['light','system','dark']as Theme[]).map(t=><button key={t}className={'choice '+(theme===t?'active':'')}onClick={()=>setThemeValue(t)}>{t==='light'?'Светлая':t==='dark'?'Тёмная':'Системная'}{theme===t&&<Check size={16}/>}</button>)}</div></section>
 <section className="panel"><h2>Рабочие блоки</h2><p className="muted">Скрывает раздел только из меню. Данные не удаляются.</p>{Object.entries<boolean>(blocks).map(([k,v])=><label className="toggle-row"key={k}><span><b>{({dashboard:'Обзор',pnl:'P&L',finances:'Финансы',budget:'Бюджет'}as Record<string,string>)[k]}</b><small>{v?'Видим':'Скрыт'}</small></span><input type="checkbox"checked={v}onChange={e=>setBlock(k,e.target.checked)}/><i/></label>)}</section>
 <section className="panel messenger-settings"><h2>Отчёты в мессенджер</h2><p className="muted">Отправка использует только подтверждённые данные STEN. Время сохраняется как настройка; автоматический scheduler подключается отдельно.</p><div className="choice-grid"><button className={'choice '+(provider==='telegram'?'active':'')}onClick={()=>setProvider('telegram')}>Telegram{provider==='telegram'&&<Check size={16}/>}</button><button className={'choice '+(provider==='whatsapp'?'active':'')}onClick={()=>setProvider('whatsapp')}>WhatsApp{provider==='whatsapp'&&<Check size={16}/>}</button></div><label className="settings-field"><span>Время отчёта</span><input type="time"value={sendTime}onChange={e=>setSendTime(e.target.value)}/></label><label className="settings-field"><span>Telegram chat ID</span><input value={telegramChat}onChange={e=>setTelegramChat(e.target.value)}placeholder="Например, -100123456789"/></label><label className="settings-field"><span>WhatsApp номер</span><input value={whatsappPhone}onChange={e=>setWhatsappPhone(e.target.value)}placeholder="79991234567"/></label><div className="messenger-metrics">{(Object.keys(metricLabels)as Array<keyof Metrics>).map(k=><label className="toggle-row"key={k}><span><b>{metricLabels[k]}</b></span><input type="checkbox"checked={metrics[k]}onChange={()=>toggleMetric(k)}/><i/></label>)}</div><button className="primary-button"disabled={messengerSaving}onClick={()=>void saveMessenger()}><Save size={16}/>{messengerSaving?'Сохраняем…':'Сохранить настройки отчётов'}</button>{messengerMessage&&<div className="pnl-message ok">{messengerMessage}</div>}</section>
 <section className="panel"><h2>AI Skills</h2><p className="muted">STEN управляется настройками, а не ручным редактированием промптов.</p><label className="settings-field"><span>Food Cost — порог %</span><input type="number"min="0"max="100"value={skills.foodCost??35}onChange={e=>setSkill('foodCost',Number(e.target.value))}/></label><label className="settings-field"><span>Labor Cost — порог %</span><input type="number"min="0"max="100"value={skills.laborCost??30}onChange={e=>setSkill('laborCost',Number(e.target.value))}/></label><label className="settings-field"><span>Длительность смены — порог часов</span><input type="number"min="1"max="24"value={skills.shiftHours??12}onChange={e=>setSkill('shiftHours',Number(e.target.value))}/></label><label className="settings-field"><span>Tone of Voice</span><select value={skills.tone??'brief'}onChange={e=>setSkill('tone',e.target.value as Skills['tone'])}><option value="brief">Кратко</option><option value="expanded">Развёрнуто</option><option value="official">Строго официально</option></select></label><label className="toggle-row"><span><b>Использовать документы</b><small>Документы входят в AI-контекст STEN.</small></span><input type="checkbox"checked={skills.documents!==false}onChange={e=>setSkill('documents',e.target.checked)}/><i/></label><label className="toggle-row"><span><b>Использовать историю</b><small>История диалога участвует в контексте.</small></span><input type="checkbox"checked={skills.history!==false}onChange={e=>setSkill('history',e.target.checked)}/><i/></label><label className="toggle-row"><span><b>Исключать Capex из OPEX trends</b><small>Разовые капитальные расходы не смешиваются с операционной динамикой.</small></span><input type="checkbox"checked={skills.excludeCapex!==false}onChange={e=>setSkill('excludeCapex',e.target.checked)}/><i/></label><div className="quick-actions"><button className="secondary-button"onClick={()=>{setSkills(defaultSkills);setSkillsMessage('Настройки возвращены к стандартным. Нажмите «Сохранить AI Skills».')}}>Сбросить Skills</button><button className="secondary-button"onClick={()=>{localStorage.removeItem('sten_chat_v5');}}>Очистить контекст диалога</button><button className="primary-button"disabled={skillsSaving}onClick={()=>void saveSkills()}><Save size={16}/>{skillsSaving?'Сохраняем…':'Сохранить AI Skills'}</button></div>{skillsMessage&&<div className="pnl-message ok">{skillsMessage}</div>} </section><section className="panel"><h2>Локальные данные</h2><p>Очистка удаляет историю и кэш только на этом устройстве. Облачные документы не удаляются.</p><button className="secondary-button"onClick={()=>void clear()}><Trash2 size={16}/> Очистить локальный кэш</button>{cleared&&<div className="pnl-message ok">Локальные данные на этом устройстве очищены. Финансовые данные на сервере не удалены.</div>}<button className="danger-button"onClick={signOut}>Завершить сессию</button></section>
 <section className="panel"><h2>Как работать</h2><ol className="guide"><li>Начинайте со STEN — сформулируйте задачу обычным языком.</li><li>Прикрепляйте Excel, PDF или документы, если они нужны для ответа.</li><li>P&L и финансовые цифры считайте в расчётных экранах, а не вручную в чате.</li><li>Проверяйте источники: отсутствие факта STEN должен обозначать прямо.</li><li>Доступ к рабочему контуру открывается только сервером после подтверждения авторизации; офлайн-вход запрещён правилами безопасности.</li></ol></section>
 </div></div>
}