import{useEffect,useMemo,useState}from'react';
import{RefreshCw,Users,AlertTriangle}from'lucide-react';
import{api,ApiError}from'../lib/api';
import{scopeQuery}from'../lib/scope';
import{useScope}from'../lib/useScope';
import{formatMoney}from'../lib/format';
type Rec={department:string;hours:number;amount:number;period:string};type Pnl={calculated?:{fact?:{revenue?:number|null;labor?:number|null};plan?:{revenue?:number|null;labor?:number|null}}};
const fmt=(n:number)=>new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(n);
const money=(n:number|null|undefined)=>n==null?'Нет данных':formatMoney(n);
export default function Team(){
 const[scope]=useScope();const[data,setData]=useState<Rec[]>([]);const[pnl,setPnl]=useState<Pnl|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[fotScopeLimited,setFotScopeLimited]=useState(false);const[fotScopeUnavailable,setFotScopeUnavailable]=useState(false);
 async function load(){setLoading(true);setError('');setFotScopeUnavailable(false);try{const q=scopeQuery(scope);let r:any=null;try{r=await api.get<any>('/fot-analytics?'+q)}catch(e){if(e instanceof ApiError&&(e.code==='FOT_SCOPE_NOT_IMPLEMENTED'||e.status===501)){setFotScopeUnavailable(true)}else{throw e}}const p=await api.get<Pnl>('/api/pnl?'+q);setData(Array.isArray(r?.records)?r.records.filter((x:Rec)=>x.period===scope.period):[]);setPnl(p)}catch(e){setData([]);setPnl(null);setError(e instanceof Error?e.message:'Не удалось загрузить ФОТ')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[scope.period,scope.projectId,scope.branchId,scope.restaurantId,scope.departmentId]);
 const grouped=useMemo(()=>{const m=new Map<string,{hours:number;amount:number}>();data.forEach(x=>{const k=x.department||'Без отдела';const v=m.get(k)||{hours:0,amount:0};v.hours+=Number(x.hours)||0;v.amount+=Number(x.amount)||0;m.set(k,v)});return[...m.entries()].sort((a,b)=>b[1].amount-a[1].amount)},[data]);
 const total=useMemo(()=>grouped.reduce((a,[,v])=>({hours:a.hours+v.hours,amount:a.amount+v.amount}),{hours:0,amount:0}),[grouped]);
 const revenue=pnl?.calculated?.fact?.revenue??null;const laborFact=pnl?.calculated?.fact?.labor??null;const laborPlan=pnl?.calculated?.plan?.labor??null;
 const laborGap=laborFact!=null&&laborPlan!=null?laborFact-laborPlan:null;const revenuePerHour=revenue!=null&&total.hours>0?revenue/total.hours:null;const hourly=total.hours>0?total.amount/total.hours:null;
 return <div className="page analytics-page team-page"><div className="page-head"><div><span className="eyebrow"><Users size={12}/> ОПЕРАЦИИ · ФОТ</span><h1>Команда</h1><p>ФОТ → часы → производительность → стоимость отклонения. Только показатели, для которых есть источник.</p></div><button className="secondary-button"onClick={()=>void load()}disabled={loading}><RefreshCw size={15}/>Обновить</button></div>
 {error&&<div className="panel empty-state"><b>ФОТ недоступен</b><span>{error}</span></div>}{fotScopeLimited&&<div className="import-result warn"><b>ФОТ доступен только на уровне организации.</b><span>Для фильтрации по ресторану/филиалу требуется подключение payroll-источника.</span></div>}{fotScopeUnavailable&&<div className="import-result warn"><b>ФОТ доступен только на уровне организации.</b><span>Для фильтрации по ресторану/филиалу требуется подключение payroll-источника.</span></div>}
 {loading?<div className="panel empty">Загружаем ФОТ…</div>:fotScopeUnavailable?<section className="panel empty-state"><b>Нет данных ФОТ для выбранного контура</b><span>P&L продолжает загружаться отдельно. После подключения payroll-источника здесь появятся часы, производительность и ФОТ по подразделениям.</span></section>:!data.length?<section className="analytics-gap-section"><div className="analytics-gap-head"><div><span className="eyebrow">КАЧЕСТВО ДАННЫХ</span><h2>Нет подтверждённого ФОТ</h2></div><AlertTriangle size={17}/></div><p>Загрузите табель или подключите payroll-источник. STEN не оценивает производительность без часов и выручки.</p></section>:<>
 <section className="analytics-kpi-strip"><div><small>ФОТ</small><strong>{money(total.amount)}</strong><span>Факт за {scope.period}</span></div><div><small>Часы</small><strong>{fmt(total.hours)}</strong><span>Подтверждённые часы</span></div><div><small>Выручка / час</small><strong>{money(revenuePerHour)}</strong><span>Выручка ÷ часы</span></div><div><small>Стоимость часа</small><strong>{money(hourly)}</strong><span>ФОТ ÷ часы</span></div><div><small>Δ ФОТ</small><strong>{money(laborGap)}</strong><span>Факт − план</span></div></section>
 <section className="panel analytics-report-section"><div className="panel-title">Экономика рабочего времени</div><div className="analytics-report-table"><div className="analytics-report-head"><span>Показатель</span><span>Значение</span><span>Источник</span><span>Правило</span></div><div><b>Производительность</b><span>{money(revenuePerHour)}</span><span>P&L + ФОТ</span><strong>выручка ÷ часы</strong></div><div><b>Стоимость часа</b><span>{money(hourly)}</span><span>ФОТ</span><strong>ФОТ ÷ часы</strong></div><div><b>Стоимость отклонения ФОТ</b><span>{money(laborGap)}</span><span>P&L план / факт</span><strong>факт − план</strong></div></div></section>
 <section className="panel analytics-report-section"><div className="panel-title">ФОТ по подразделениям</div><div className="analytics-report-table labor-table"><div className="analytics-report-head"><span>Подразделение</span><span>Часы</span><span>ФОТ</span><span>₽ / час</span></div>{grouped.map(([d,v])=><div key={d}><b>{d}</b><span>{fmt(v.hours)} ч</span><span>{money(v.amount)}</span><strong>{v.hours?money(v.amount/v.hours):'Нет данных'}</strong></div>)}<div className="analytics-report-total"><b>Итого</b><span>{fmt(total.hours)} ч</span><strong>{money(total.amount)}</strong><span>{money(hourly)}</span></div></div></section>
 <section className="analytics-gap-section"><div className="analytics-gap-head"><div><span className="eyebrow">СЛЕДУЮЩИЙ СЛОЙ</span><h2>Что появится после подключения графика</h2></div></div><div className="analytics-gap-list"><span>План / факт часов</span><span>Переработки по сотруднику</span><span>Выручка на сотрудника</span><span>Потребность по daypart</span></div><p>Производительность рассчитана только из подтверждённых выручки и часов; планирование смен пока не подключено.</p></section></>}</div>}
